version: "3.7"
services:
  app:
    container_name: app-escritorio
    image: dev/sisescritorio
    ports:
     - "6001:6001"
    build:
      args:
        user: dockerd
        uid: 1000
      context: ./php-fpm
    restart: unless-stopped
    working_dir: /var/www/escritorio
    volumes:
      - ./escritorio:/var/www/escritorio
    networks:
      - backend
  nginx:
    image: nginx:1.17-alpine
    restart: unless-stopped
    container_name: nginx-escritorio
    user: root
    ports:
      - 8021:80
    volumes:
      - ./escritorio:/var/www/escritorio
      - ./nginx/sites:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
    networks:
      - backend
  db:
    image: mysql
    container_name: db-escritorio
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: escritorio
      MYSQL_USER: escritorio
      MYSQL_PASSWORD: escritorio

networks:
  backend:
    driver: bridge
volumes:
  db_data:
    driver: local
